---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksmani
  region: ap-southeast-2
  tags:
    project: linkedin-learning

nodeGroups:
  - name: worker-node
    instanceType: m5.large
    desiredCapacity: 3
